### ISSUE TITLE
No option for Exceptional Equipment?

### ISSUE THREAD

**Issue by nick012000** [frankwking/WiseArtificersInsight#3]
On p. 580 of the Exalted 3e corebook it says that Exceptional Equipment grants a bonus of +1 non-charm dice on rolls to use it. However, there's no option on Wise Artificer's Insight that allows you to take that into consideration when you're calculating your dice pool probabilities. Would it be possible for you to add an "Exceptional Equipment" button that adds an additional die to your dice pool when ticked?

**Comment by frankwking** [comment]
Yup, that can get added.  Its been a long time since I've worked on the site it make take a second.

**Comment by frankwking** [comment]
I've added it.  Please confirm that you can see it on the live website and I'll close the issue.

**Comment by nick012000** [comment]
I can confirm that I can see it on the site, and it appears to be working. Thanks!
